export {default as CheckCircleSvg} from './CheckCircle';
export {default as StepSvg} from './Step';
export {default as RightArrowSvg} from './RightArrow';
export {default as SwitchSvg} from './Switch';
export {default as CertificateSvg} from './Certificate';
export {default as LoadingSvg} from './Loading';
export {default as ResetSvg} from './Reset';
export {default as TipSvg} from './Tips';
export {default as LookSvg} from './Look';